-- MySQL Script generated by MySQL Workbench
-- Wed Mar 16 02:20:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema assig1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assig1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assig1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `assig1` ;

-- -----------------------------------------------------
-- Table `assig1`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assig1`.`hibernate_sequence` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assig1`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assig1`.`user` (
  `id` INT NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_jreodf78a7pl5qidfh43axdfb` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assig1`.`vacationdestination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assig1`.`vacationdestination` (
  `id` INT NOT NULL,
  `destinationName` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_p6bxive891621njf18e1u7wdf` (`destinationName` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assig1`.`vacationpackage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assig1`.`vacationpackage` (
  `id` INT NOT NULL,
  `currentBooked` INT NULL DEFAULT NULL,
  `endTime` DATE NULL DEFAULT NULL,
  `extraDetails` VARCHAR(255) NULL DEFAULT NULL,
  `maxBooked` INT NULL DEFAULT NULL,
  `packageName` VARCHAR(255) NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `startTime` DATE NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `vacantiondestination_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKfotbumgv83cwg2v8enn1dcvpe` (`vacantiondestination_id` ASC) VISIBLE,
  CONSTRAINT `FKfotbumgv83cwg2v8enn1dcvpe`
    FOREIGN KEY (`vacantiondestination_id`)
    REFERENCES `assig1`.`vacationdestination` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `assig1`.`user_vac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assig1`.`user_vac` (
  `user_id` INT NOT NULL,
  `vac_id` INT NOT NULL,
  INDEX `FK6gpqbyxaaiaqlf18tb3d8cyn1` (`vac_id` ASC) VISIBLE,
  INDEX `FKbcfeimpw7l748opmjsvtpol61` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK6gpqbyxaaiaqlf18tb3d8cyn1`
    FOREIGN KEY (`vac_id`)
    REFERENCES `assig1`.`vacationpackage` (`id`),
  CONSTRAINT `FKbcfeimpw7l748opmjsvtpol61`
    FOREIGN KEY (`user_id`)
    REFERENCES `assig1`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
